pool:
  vmImage: 'vs2017-win2016'
  
variables:
  - group: 'Deploy'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    configuration: '$(BuildConfiguration)'
    zipAfterPublish: true

- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: '$(Deploy.ServiceConnectionName)'
    resourceGroupName: '$(Deploy.ResourceGroupName)'
    location: '$(Deploy.Location)'
    templateLocation: 'Linked artifact'
    csmFile: 'deployment\template.json'
    overrideParameters: '-stackName $(Build.SourceBranchName)'