pool:
  vmImage: 'vs2017-win2016'
  
variables:
- group: Deploy

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      dotnet publish --configuration $env:BuildConfiguration --output $env:Build_ArtifactStagingDirectory
      Compress-Archive -Path $env:Build_ArtifactStagingDirectory\*

- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: '$(ServiceConnectionName)'
    resourceGroupName: '$(ResourceGroupName)'
    location: '$(Location)'
    templateLocation: 'Linked artifact'
    csmFile: 'deployment\template.json'
    overrideParameters: '-stackName $(Build.SourceBranchName)'