pool:
  vmImage: 'vs2017-win2016'
  
variables:
- group: Deploy

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
    dotnet publish --configuration $env:BuildConfiguration --output $env:Build_ArtifactStagingDirectory
    Write-Host "ServiceConnectionName: $env:ServiceConnectionName"

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    configuration: '$(BuildConfiguration)'
    zipAfterPublish: true
    projects: Eklee.Exams.Api\Eklee.Exams.Api.csproj

- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: '$(ServiceConnectionName)'
    resourceGroupName: '$(ResourceGroupName)'
    location: '$(Location)'
    templateLocation: 'Linked artifact'
    csmFile: 'deployment\template.json'
    overrideParameters: '-stackName $(Build.SourceBranchName)'