pool:
  vmImage: 'vs2017-win2016'
  
variables:
- group: Deploy

steps:

- task: CmdLine@2
  inputs:
    script: dotnet publish --configuration %Deploy_BuildConfiguration%

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    configuration: '$(Deploy.BuildConfiguration)'
    zipAfterPublish: true
    projects: Eklee.Exams.Api\Eklee.Exams.Api.csproj

- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'ekleesc1'
    resourceGroupName: '$(Deploy.ResourceGroupName)'
    location: '$(Deploy.Location)'
    templateLocation: 'Linked artifact'
    csmFile: 'deployment\template.json'
    overrideParameters: '-stackName $(Build.SourceBranchName)'